import { AlbumModel } from "../../Types/Album";

export const IntialData:AlbumModel={
    wrapperType: "",
    kind: "",
    collectionId: 0,
    trackId: 0,
    artistName: "",
    collectionName: "",
    trackName: "",
    collectionCensoredName: "",
    trackCensoredName: "",
    collectionArtistId: 0,
    collectionArtistViewUrl: "",
    collectionViewUrl: "",
    trackViewUrl: "",
    previewUrl: "",
    artworkUrl30: "",
    artworkUrl60: "",
    artworkUrl100: "",
    collectionPrice: 0,
    trackPrice: 0,
    trackRentalPrice: 0,
    collectionHdPrice: 0,
    trackHdPrice: 0,
    trackHdRentalPrice: 0,
    releaseDate: new Date(),
    collectionExplicitness: "",
    trackExplicitness: "",
    discCount: 0,
    discNumber: 0,
    trackCount: 0,
    trackNumber: 0,
    trackTimeMillis: 0,
    country: "",
    currency: "",
    primaryGenreName: "",
    contentAdvisoryRating: "",
    shortDescription: "",
    longDescription: "",
    hasITunesExtras: false
}